### ISSUE TITLE
不支持edxposed，麻烦博主能更新下

### ISSUE THREAD

**Issue by pkw123456** [Mocha-L/QuJing#1]

**Comment by jionecc** [comment]
支持啊,我android 10 edxposed+Magisk支持啊

**Comment by axhlzy** [comment]
测试 pixel xl 刷的安卓8.0 部分app 在端口转发之后能够正常进入配置

**Comment by Mocha-L** [comment]
经过测试
qujing支持edxposed 可以排查下是否有白名单等原因导致插件未加载
