### ISSUE TITLE
怎么感觉没生效

### ISSUE THREAD

**Issue by zxcvbn001** [Mocha-L/QuJing#18]
![image](https://github.com/Mocha-L/QuJing/assets/23741141/4995ea2a-35dc-4de4-ac40-e84096327bb8)

夸克访问很多站一个包没有

**Comment by Mocha-L** [comment]
@zxcvbn001 sorry 报文功能 是一个Demo能力
如果APP本身不依赖底层基础库，该功能就失效了，可以看看别的app是否支持哈～
