### ISSUE TITLE
建议把apk放到release里面

### ISSUE THREAD

**Issue by chenyue404** [Mocha-L/QuJing#4]
不然几个版本之后，git文件夹会变得非常大。

**Comment by Mocha-L** [comment]
okk 多谢建议 我搞一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月7日(周三) 中午11:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Mocha-L/QuJing] 建议把apk放到release里面 (#4)




 
不然几个版本之后，git文件夹会变得非常大。

**Comment by Mocha-L** [comment]
Done
