### ISSUE TITLE
无法启动apk

### ISSUE THREAD

**Issue by xmhwws** [Mocha-L/QuJing#6]
安卓10
pixel2
edxposed

release的2个apk都试过，安装后没有打开按钮，手机里面不显示apk图标，通过MT强制启动就报错：
![2021-08-04_16-05-17](https://user-images.githubusercontent.com/42903751/128145517-a9117f75-cbd9-4a14-9a96-566a1423466b.png)

edxposed倒是能识别出模块

**Comment by Mocha-L** [comment]
老兄 你看下使用的文档哇
这个是无图标无界面的 不需要你启动 会附加到需要的apk上的
