### ISSUE TITLE
http://127.0.0.1:61000 无法打开 ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by miqt** [Mocha-L/QuJing#8]
环境：
小米10，Android 11 magisk 23  LSPosed 1.6.5，win10

现象：
按照使用方法操作，无法打开网页页面

![image](https://user-images.githubusercontent.com/15975726/144961688-9634bf87-7997-4a22-9e55-2cfb7575c58f.png)

怎么排查？

**Comment by miqt** [comment]
尝试直接访问手机IP也不行，更换路由器也无效果

**Comment by Mocha-L** [comment]
adb forward有没有转发61000啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月7日(周二) 中午11:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Mocha-L/QuJing] http://127.0.0.1:61000 无法打开 ERR_EMPTY_RESPONSE (Issue #8)




 
尝试直接访问手机IP也不行，更换路由器也无效果
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by miqt** [comment]
尝试这个项目是可以的，是否考虑调整展示方式

https://github.com/amitshekhariitbhu/Android-Debug-Database

**Comment by miqt** [comment]
这个执行了
>adb forward tcp:61000 tcp:61000
61000

**Comment by miqt** [comment]
能看到这样的日志：

![image](https://user-images.githubusercontent.com/15975726/144962459-9a6a1940-7f9e-479a-860d-e8a66a1a659a.png)

**Comment by miqt** [comment]
![image](https://user-images.githubusercontent.com/15975726/145024210-f9ed9029-a0a7-4c16-9e01-6ea5af247715.png)
这个判断的问题，我改了下启动入口好像没问题了

**Comment by Mocha-L** [comment]
不确定是不是安卓高版本的问题 
服务没有挂载启动成功

**Comment by miqt** [comment]
我用的LSPosed，不设置挂载系统框架应该是不会触发启动61000端口，我改了下包名等于我想测试的应用时，启动61000端口就好了
其次提个建议，我看 XServer 有个当前app所有类的展示感觉挺方便使用的，建议加一个，逆向的时候带壳包可能不知道当前app都有那些类，要是能借助xposed列出来所有的类库会方便很多

**Comment by miqt** [comment]
其实我觉得61000这个端口甚至可以不启用，把选择调试应用的页面放在手机端曲镜app里面选择，目标app启动后，监控弹窗提示当前应用监听端口，PC上直接打开进行调试就好了
这样做的好处是：
1. 不用把模块挂载到系统框架，可以有效避免有的机型系统挂载xposed模块后无法开机的风险
2. 方便操作，可以直接在手机端选择完成后直接打开目标app开始调试，并弹窗提示本app专属连接地址：http://手机ip/端口
3. 可以略过 adb forward tcp:61000 tcp:61000 这一步，直接打开http://手机ip/端口 就可以了，（现在貌似也可以，只是不方便查看app对应的pid和手机ip地址）

**Comment by Mocha-L** [comment]
首先感谢miqt大佬对曲境的体验和众多建议。
首先，曲境也是来自于XServer的。我在改写和新增功能时，其实主要是想让整个逻辑越来越简单和便捷。但是由于个人习惯等等原因，可能无法match所有用户的使用场景。下面回复你一下你的几个建议
1. APP所有类的功能   ----这个是我故意拿掉的，因为在我看来，用曲境是和逆向工具配合使用的，我们在jadx/jeb等找到怀疑的类时，用qujing来定向hook，反而展示太多的东西用不到还繁杂。确实忽略了你说的带壳包的场景，我在想遇到这种情况不是应该先脱壳么，在未脱壳的时候看到这些类进行hook，是否有这个必要呢，这一点需要探讨一下。
2. 取消挂载的主进程，在app上做这一部分事情 ----如果如你这样设计，的确有一些好处，比如你说的避免了主进程挂载失败的场景和目前无法开机hook的场景。但是也有了一些问题，就是我的使用方法整个会变得麻烦一些，为了让整个使用无门槛和好入门，我避免了在app的所有操作（除了装插件），而只要进入首页，后续的操作流程都有我的指引和说明，这样会对使用者更友好。不过你提到的这个思路呢，确实也可以考虑作为双方案并行来解决上述提到的两个问题（主进程挂载和开机hook）。
最后再次感谢miqt的使用和建议，也非常欢迎加入到qujing的优化和丰富之中。 
@miqt
